//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class faiblecontre
    {
        public Nullable<decimal> modificateur { get; set; }
        public sbyte id_types { get; set; }
        public sbyte id_types_1 { get; set; }
    
        public virtual types types { get; set; }
        public virtual types types1 { get; set; }
    }
}
