//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class gagne
    {
        public Nullable<System.DateTime> obtention { get; set; }
        public int id_dresseur { get; set; }
        public sbyte id_badges { get; set; }
    
        public virtual badges badges { get; set; }
        public virtual dresseurs dresseurs { get; set; }
    }
}
