//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pokesandraEntities : DbContext
    {
        public pokesandraEntities()
            : base("name=pokesandraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arenes> arenes { get; set; }
        public virtual DbSet<attaques> attaques { get; set; }
        public virtual DbSet<badges> badges { get; set; }
        public virtual DbSet<dresseurs> dresseurs { get; set; }
        public virtual DbSet<faiblecontre> faiblecontre { get; set; }
        public virtual DbSet<fortcontre> fortcontre { get; set; }
        public virtual DbSet<gagne> gagne { get; set; }
        public virtual DbSet<npc> npc { get; set; }
        public virtual DbSet<objets> objets { get; set; }
        public virtual DbSet<pokedex> pokedex { get; set; }
        public virtual DbSet<pokemons> pokemons { get; set; }
        public virtual DbSet<positions> positions { get; set; }
        public virtual DbSet<typedepokemons> typedepokemons { get; set; }
        public virtual DbSet<typeobjet> typeobjet { get; set; }
        public virtual DbSet<types> types { get; set; }
        public virtual DbSet<zones> zones { get; set; }
    }
}
