//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class objets
    {
        public int id_objet { get; set; }
        public string nom { get; set; }
        public sbyte quantite { get; set; }
        public Nullable<int> id_nonjoueur { get; set; }
        public sbyte id_typeObjet { get; set; }
    
        public virtual npc npc { get; set; }
        public virtual typeobjet typeobjet { get; set; }
    }
}
