//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokemons
    {
        public int id_pokemons { get; set; }
        public string surnom { get; set; }
        public Nullable<sbyte> niveau { get; set; }
        public System.DateTime capture { get; set; }
        public int id_dresseur { get; set; }
        public short id_attaques { get; set; }
        public short id_attaques_1 { get; set; }
        public short id_attaques_2 { get; set; }
        public short id_attaques_3 { get; set; }
        public short id_type_pokemons { get; set; }
    
        public virtual attaques attaques { get; set; }
        public virtual attaques attaques1 { get; set; }
        public virtual attaques attaques2 { get; set; }
        public virtual attaques attaques3 { get; set; }
        public virtual dresseurs dresseurs { get; set; }
        public virtual typedepokemons typedepokemons { get; set; }
    }
}
