//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class typedepokemons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public typedepokemons()
        {
            this.pokemons = new HashSet<pokemons>();
            this.typedepokemons1 = new HashSet<typedepokemons>();
            this.typedepokemons2 = new HashSet<typedepokemons>();
            this.types = new HashSet<types>();
            this.zones = new HashSet<zones>();
        }
    
        public short id_type_pokemons { get; set; }
        public string nom { get; set; }
        public Nullable<short> attaque { get; set; }
        public Nullable<short> attaque_spe { get; set; }
        public Nullable<short> defence { get; set; }
        public Nullable<short> defence_spe { get; set; }
        public Nullable<short> vitesse { get; set; }
        public Nullable<short> pv { get; set; }
        public short id_pokedex { get; set; }
    
        public virtual pokedex pokedex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pokemons> pokemons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<typedepokemons> typedepokemons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<typedepokemons> typedepokemons2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<types> types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zones> zones { get; set; }
    }
}
